Removing 'divide by zero' warnings
leximpact/openfisca-france-dotations-locales pull request #15
Opened 2021-04-09 08:25 UTC by Sasha-Laniece

* Changement mineur.
* Périodes concernées : toutes.
* Zones impactées : `openfisca_france_dotations_locales/variables/base.py`.
* Détails :
  - Suppression des warnings 'divide by zero' dans la fonction custom de division que nous avons écrite (et qui fait bien attention à ne pas diviser par zéro)
  
- - - -

Ces changements:
- Corrigent ou améliorent un calcul déjà existant.

- - - -

2021-04-09 08:52 UTC, benoit-cty approved these changes
OK pour moi.

2021-04-09 12:15 UTC, benoit-cty commented
Peut-être faire une action plus localisé avec :
`with np.errstate(divide='ignore', invalid='ignore'):
    # the division code here
`

2021-04-20 16:56 UTC, benoit-cty requested changes
Hello,
J'ai l'impression qu'il faut vérifier certaines choses avec magemax.

2021-04-20 16:56 UTC, benoit-cty commented on openfisca_france_dotations_locales/variables/dotation_forfaitaire.py
> +        facteur_du_coefficient_logarithmique = safe_divide(1, log10(safe_divide(plafond_dgcl_population_dgf_majoree, plancher_dgcl_population_dgf_majoree, 1)), 0)  # le fameux 0.38431089
Ici, on change potentiellement le comportement en évitant une division par zéro qu'on ne voulait pas éviter avant. Est-ce bien ce qu'on souhaite ?

2021-04-20 16:56 UTC, benoit-cty commented on openfisca_france_dotations_locales/variables/dotation_forfaitaire.py
> +        dotation_supp_par_habitant = facteur_minimum + (facteur_maximum - facteur_minimum) * max_(0, min_(1, facteur_du_coefficient_logarithmique * log10(safe_divide(population_majoree_dgf, plancher_
Ici, on change potentiellement le comportement en évitant une division par zéro qu'on ne voulait pas éviter avant. Est-ce bien ce qu'on souhaite ?

2021-04-20 16:56 UTC, benoit-cty commented on openfisca_france_dotations_locales/variables/dotation_solidarite_rurale_fractions/cible.py
> +        facteur_pot_fin = max_(0, safe_divide((2 * pot_fin_par_hectare_10000 - potentiel_financier_par_habitant), pot_fin_par_hectare_10000, 0))
Ici, on change potentiellement le comportement en évitant une division par zéro qu'on ne voulait pas éviter avant. Est-ce bien ce qu'on souhaite ?

2021-04-20 16:56 UTC, benoit-cty commented on openfisca_france_dotations_locales/variables/dotation_solidarite_rurale_fractions/cible.py
> +        pot_fin_par_hectare_10000 = safe_divide(np.sum(communes_moins_10000 * potentiel_financier), np.sum(communes_moins_10000 * superficie))
Ici, on change potentiellement le comportement en évitant une division par zéro qu'on ne voulait pas éviter avant. Est-ce bien ce qu'on souhaite ?

2021-04-20 16:56 UTC, benoit-cty commented on openfisca_france_dotations_locales/variables/dotation_solidarite_rurale_fractions/cible.py
> +        facteur_pot_fin = max_(0, 2 - safe_divide(potentiel_financier_par_habitant, potentiel_financier_par_habitant_strate, 2))
Ici, on change la valeur par défaut de retour, mais au final, on retombe sur la même chose car s'il y a division par 0 on a max(0, 2 - 2) == 0, c'est bien ça ?
Mais si potentiel_financier_par_habitant_strate est négatif et que le résultat de la division est légèrement positif, 1 par exemple, on va obtenir max(0, 2 - 1) == 1, ce qui change le comportement, non ?

2021-04-20 16:56 UTC, benoit-cty commented on openfisca_france_dotations_locales/variables/agglomeration.py
> +        return safe_divide(population_dgf_agglomeration, population_dgf_departement_agglomeration, 0)
Je me demande si on aurait pas dû ajouter un paramètre pour indiquer le sens de la comparaison du where : Le safe_divide autorise des chiffres négatifs, alors que les formules du code testent souvent que le dénominateur est positif.

2021-04-21 06:48 UTC, Sasha-Laniece commented on openfisca_france_dotations_locales/variables/agglomeration.py
> +        return safe_divide(population_dgf_agglomeration, population_dgf_departement_agglomeration, 0)
Pour moi la question ne se pose pas pour les calculs, car les chiffres de population sont toujours positifs. Mais effectivement c'est un contrôle en moins

2021-04-21 07:02 UTC, Sasha-Laniece commented on openfisca_france_dotations_locales/variables/dotation_solidarite_rurale_fractions/cible.py
> +        facteur_pot_fin = max_(0, 2 - safe_divide(potentiel_financier_par_habitant, potentiel_financier_par_habitant_strate, 2))
Effectivement. J'avais misé sur le fait que ce chiffre ne peut pas etre négatif. À voir avec @magemax si c'est une possibilité

2021-04-22 11:18 UTC, benoit-cty approved these changes
Merci

2021-04-22 11:18 UTC, merged