Zero habitant
leximpact/openfisca-france-dotations-locales pull request #5
Opened 2020-06-29 08:39 UTC by magemax

renvoie zero quand le denominateur est nul dans une division.

2020-07-09 10:41 UTC, sandcha requested changes
Principalement en raison d'un test qui ne passait pas (correction proposée en commit) et une répétition de conditions pré-divide et dans le where du divide qui me semble étrange.

2020-07-09 10:41 UTC, sandcha commented on openfisca_france_dotations_locales/variables/dotation_solidarite_rurale_fractions/cible.py
> +            * (population_dgf > 0)
`population_dgf` n'est pas employé directement dans le calcul ci-dessous. J'ai testé sa suppression et je n'ai pas vu son effet ; il me semble que la condition est déjà introduite là où nous en avons besoin. 
Si on tient à la garder, la déplacer à proximité de sa zone (aka variable) d'impact pour ne pas la noyer ?
```suggestion
```

2020-07-09 10:41 UTC, sandcha commented on openfisca_france_dotations_locales/variables/agglomeration.py
> +        return (population_dgf_departement_agglomeration > 0) * np.divide(population_dgf_agglomeration, population_dgf_departement_agglomeration, where = (population_dgf_departement_agglomeration > 0
Pourquoi indiquons-nous deux fois la condition ? En terme de calcul, np.divide optimise-t-il pas déjà en fonction de sa propriété `where` ?
```suggestion
        return np.divide(population_dgf_agglomeration, population_dgf_departement_agglomeration, where = (population_dgf_departement_agglomeration > 0))
```

Testé sous ipython et cela renvoie bien 0. lorsque le dénominateur est à zéro.

2020-07-09 10:41 UTC, sandcha commented on openfisca_france_dotations_locales/variables/potentiel_financier.py
> +        return (population_dgf > 0) * np.divide(commune('potentiel_financier', period), population_dgf, where = (population_dgf > 0))
De même, ne pas indiquer la condition deux fois ? 🤔 
```suggestion
        return np.divide(commune('potentiel_financier', period), population_dgf, where = (population_dgf > 0))
```

2020-07-09 10:41 UTC, sandcha commented on openfisca_france_dotations_locales/variables/revenu.py
> +        return (population_insee > 0) * np.divide(commune('revenu_total', period), population_insee, where = (population_insee > 0))
De même : 
```suggestion
        return np.divide(commune('revenu_total', period), population_insee, where = (population_insee > 0))
```

2020-07-09 10:41 UTC, sandcha commented on openfisca_france_dotations_locales/variables/dotation_solidarite_rurale_fractions/cible.py
> +            * (population_dgf > 0)
Cette condition pourra faire passer le test amendé dans le dernier commit (je n'ai pas vu que cela génèrerait une erreur des tests en commitant mais je le laisse pour éviter un force-push durant nos échanges 😬).

2020-07-09 13:28 UTC, magemax commented on openfisca_france_dotations_locales/variables/agglomeration.py
au lieu de  

    np.divide(a, b, where = (b>0) )  

on peut utiliser 

    np.where(b>0, a/b, 0)  

qui est peut être plus clair

2020-07-13 13:23 UTC, sandcha approved these changes
Merci pour ce code concis et lisible :)

2020-07-13 13:24 UTC, merged