Montants dsr : les trois fractions.
leximpact/openfisca-france-dotations-locales pull request #7
Opened 2020-07-09 09:25 UTC by magemax

PR calculant le montant (hors garantie) des trois fractions de la DSR.

- Le montant de la fraction cible est littéralement le même que la fraction péréquation (et a priori on ne changera pas cet état de fait dans les réformes possibles prévues) donc peut être que copier/coller comme j'ai fait est un peu bourrin et qu'on pourrait réduire la taille du code

- Tous les mécanismes de calculs ont le même schéma global de fonctionnement : un montant global à attibuer aux communes éligibles est déterminé. Puis un score d'attribution est calculé pour chaque commune éligible, puis le montant global est réparti au prorata de ce score. Ce mécanisme arrive 9 fois dans la DSR ( 4 fois pour péréquation et cible, et une pour bourg-centre), à chaque fois on crée 4 variables (montant global attribué, score d'attribution, valeur du point et montant final résultant).  Peut-être qu'on pourrait trouver un moyen de le faire plus économiquement  en lignes de codes (i.e. calculer un truc qui calcule automatiquement avec comme variables le montant global attribué et la formule du score d'attribution)

- Les mêmes paramètres d'attribution s'appliquent à la fraction péréquation et à la fraction cible. Je les ai donc rassemblés dans dotation_solidarite_rurale.attribution    , mais ça n'est pas forcément la bonne approche. On pourrait aussi créer un 
dotation.solidarite_rurale.perequation_et_cible.attribution.

- les variables finales sont pour l'instant du type "dsr_montant_hors_garanties_fraction_bourg_centre" ,  la variable "dsr_fraction_bourg_centre"  n'est pas encore liée.  Il y manque (elon les textes) les garanties aux communes nouvelles, aux communes nouvellement non éligibles, et les garanties de stabilité.

@sandcha

2020-07-13 14:23 UTC, sandcha requested changes
1ers retours.

2020-07-13 14:23 UTC, sandcha commented on CHANGELOG.md
> +## 0.2.1 [#7](https://github.com/leximpact/openfisca-france-dotations-locales/pull/7)
Comme nous ajoutons des variables, ce serait plutôt un bump mineur :
```suggestion
## 0.3.0 [#7](https://github.com/leximpact/openfisca-france-dotations-locales/pull/7)
```

> Ce qu'on dit de façon succincte dans le [CONTRIBUTING.md](https://github.com/leximpact/openfisca-france-dotations-locales/blob/master/CONTRIBUTING.md#version-number)

2020-07-13 14:23 UTC, sandcha commented on openfisca_france_dotations_locales/parameters/dotation_solidarite_rurale/attribution/poids_potentiel_financier_par_hectare.yaml
> +description: Part de la DSR (péréquation et cible) répartie en fonction du potentiel financier par hectare
> Les paramètres peuvent également être réunis dans le même fichier. On pourrait avoir quelque chose comme `poids_potentiel_financier.par_habitant` et `poids_potentiel_financier.par_hectare`.

2020-07-13 14:23 UTC, sandcha commented on openfisca_france_dotations_locales/variables/dotation_solidarite_rurale_fractions/bourg_centre.py
> +    def formula(commune, period, parameters):
Dans ce cas particulier de montants en dur dans le code, dater la formule ?

2020-07-13 14:23 UTC, sandcha commented on openfisca_france_dotations_locales/variables/dotation_solidarite_rurale_fractions/bourg_centre.py
> +        montant_total_a_attribuer = 545_248_126 - 898_172 - 6_165_344
Typo dans le montant de la masse de crédits mis en répartition ? Dans la note page 9 il est dit : 
"La masse des crédits mis en répartition en métropole au titre de l'année 2019 s’élève à 45 248 126 €."
```suggestion
        montant_total_a_attribuer = 45_248_126 - 898_172 - 6_165_344
```

2020-07-13 14:25 UTC, sandcha commented on openfisca_france_dotations_locales/variables/dotation_solidarite_rurale_fractions/bourg_centre.py
> +        montant_total_a_attribuer = 545_248_126 - 898_172 - 6_165_344
Mais effectivement, page 2, il est dit : "545 248 129 € sont répartis au titre de la fraction « bourg - centre » (7,56 %)"

2020-07-13 15:14 UTC, sandcha commented on CHANGELOG.md
> +## 0.2.1 [#7](https://github.com/leximpact/openfisca-france-dotations-locales/pull/7)
Done au rebase.

2020-07-13 22:54 UTC, magemax reviewed
Hmmm il faudra floorer à zéro le score lié au potentiel financier par hectare (et updater les tests) : avec le code d'aujourd'hui, le score peut être négatif.

2020-07-13 22:54 UTC, magemax commented on openfisca_france_dotations_locales/variables/dotation_solidarite_rurale_fractions/perequation.py
> +        facteur_pot_fin = 2 - potentiel_financier_par_habitant / pot_fin_par_hectare_10000
Là ça sent pas bon : contrairement aux autres fois où cette équation est utilisée, il n'y a pas de plafond à 2 x le potentiel financier moyen. Donc appliquer stricto sensu la formule qui apparaît dans le PDF est foireux (Je m'en suis rendu compte en voyant mes résultats par rapport à la DGCL sur cette colonne en particulier). 

Peut être que le floorer à zéro suffira, l'investigation est en cours.

2020-07-16 08:11 UTC, sandcha approved these changes
Top ! Sera probablement amendé suite à la confrontation avec les données DGCL sur `leximpact-server`.

2020-07-16 08:11 UTC, sandcha commented on openfisca_france_dotations_locales/variables/dotation_solidarite_rurale_fractions/bourg_centre.py
> +                / np.sum(communes_moins_10000 * population_dgf))
> Cette formule revient plusieurs fois dans ce fichier. En faire une variable intermédiaire d'autant qu'elle a un sens métier clair ?

2020-07-16 08:11 UTC, sandcha commented on openfisca_france_dotations_locales/variables/zrr.py
> +    reference = ["https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006069577&idArticle=LEGIARTI000006306203",
👍

2020-07-16 08:11 UTC, sandcha commented on openfisca_france_dotations_locales/variables/dotation_solidarite_rurale_fractions/bourg_centre.py
> +    entity = Commune
> Introduire une entité `Etat` ? 🤔

2020-07-16 08:11 UTC, sandcha commented on openfisca_france_dotations_locales/variables/dotation_solidarite_rurale_fractions/perequation.py
> +        part_potentiel_financier_par_hectare = commune('dsr_fraction_perequation_part_potentiel_financier_par_hectare', period)
> Nous pourrions réduire la longueur des noms de variables en supprimant `fraction_`, voire `part_` aussi.

2020-07-16 08:11 UTC, sandcha commented on openfisca_france_dotations_locales/variables/dotation_solidarite_rurale_fractions/perequation.py
> +    entity = Commune
> Là aussi, la valeur étant identique à toute commune éligible, l'entité devrait être plus large. Etat ? 🤔

2020-07-16 08:11 UTC, sandcha commented on openfisca_france_dotations_locales/variables/dotation_solidarite_rurale_fractions/bourg_centre.py
> +        montant_total_a_attribuer = 545_248_126 - 898_172 - 6_165_344
> Ces montants devraient figurer en paramètres.

2020-07-16 08:11 UTC, sandcha commented on openfisca_france_dotations_locales/variables/dotation_solidarite_rurale_fractions/perequation.py
> +        return montant_total_a_attribuer / score_total
Risque de division par zero.
```suggestion
        return where(score_total > 0., montant_total_a_attribuer / score_total, 0.)
```

2020-07-16 08:11 UTC, sandcha commented on openfisca_france_dotations_locales/variables/dotation_solidarite_rurale_fractions/perequation.py
> +class dsr_montant_total_eligibles_fraction_perequation(Variable):
Renommer en `dsr_montant_perequation` ? Ceci sachant qu'on manipule une liste de communes (donc on sait que ce n'est pas le montant national) et que cette liste couvre toutes les communes (même les non éligibles auront une valeur qui devrait être à zéro).

2020-07-16 08:45 UTC, sandcha commented
@magemax Pour répondre aux interrogations exprimées ci-dessus : 

> Le montant de la fraction cible est littéralement le même que la fraction péréquation (et a priori on ne changera pas cet état de fait dans les réformes possibles prévues) donc peut être que copier/coller comme j'ai fait est un peu bourrin et qu'on pourrait réduire la taille du code

On pourrait effectivement mettre en commun des variables. Il y en a de plusieurs sortes. 
On pourrait utiliser une variable pour les scores. Ceci dit, je ne suis pas certaine que cela nous rende service pour les réformes, sauf à conserver la dépendance de principe entre péréquation et cible pour l'usager. 
Il y a aussi des variables plutôt de l'ordre du helper mais qui prendraient sens au niveau métier (les moyennes où fait appel au sum numpy par exemple) qui elles pourraient être extraites sans impacter la réforme.

> Les mêmes paramètres d'attribution s'appliquent à la fraction péréquation et à la fraction cible. Je les ai donc rassemblés dans dotation_solidarite_rurale.attribution , mais ça n'est pas forcément la bonne approche. On pourrait aussi créer un dotation.solidarite_rurale.perequation_et_cible.attribution.

Toujours dans l'esprit des réformes, je pense qu'on préfèrera les manipuler fraction par fraction et qu'il serait mieux de les séparer même si aujourd'hui les valeurs sont identiques.
De manière générale, se pose aussi la question des perspectives d'évolution de la loi. Si c'est dans son esprit et a de grandes chances de le rester de structurer cible et péréquation de la même manière, cela prend sens de les rassembler et de les relier dans leximpact-client.

2020-07-21 08:28 UTC, merged